// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pskxileirrvjnuiadfcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBza3hpbGVpcnJ2am51aWFkZmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTgwODEsImV4cCI6MjA3NDI3NDA4MX0.J1XaMti1lJn5tZVH9RUAS-2cYoMvYG_AW_AX4i0XmXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});